### PR TITLE
247 admin panel sponsor

### PR DESCRIPTION
**Pull request by ivanzaqqa**
#247 

### Breakdown:
-  show logs of sponsor
- add create logs button on each sponsor row

### CODE REVIEW

**Comment by ivanzaqqa** [comment]
to be review mas

**Comment by andy-shi88** [comment]
have you finish this one? if so please solve the conflicts first.

**Comment by andy-shi88** [comment]
@ivanzaqqa

**Comment by ivanzaqqa** [comment]
Oke mas, I will be fix the conflicts,

**Comment by andy-shi88** [comment]
I'll solve the conflicts it's needed ASAP

**Pull request merged**
