### PR TITLE
PR-243 entry ambassador

### PR DESCRIPTION
**Pull request by erdivartanovich**
#243 fix

### Breakdown:
- [x] Add ambassador management
- [x] Modify account page to manage attendee, speaker, booth, and ambassador

### Need to resolve
- [ ] There is still no migration for Ambassador table. I leave this to others, just follow the model
- [ ] Need to resolve how to link account management and set password page (#213)
- [x] Need to return attendee, speaker, booth, and ambassador from ```get:/users/<id>``` endpoint, the one like Role Include mechanism

### CODE REVIEW

**Comment by erdivartanovich** [comment]
account_edit and account_add was removed in this changes since I use single model (account_input) for both operation

**Comment by erdivartanovich** [comment]
@andy-shi88 dynamic include already implemented and relations fields also displayed
sure, this one is fine now

**Comment by andy-shi88** [comment]
nice, I'll check once I'm on my laptop, thanks

**Comment by andy-shi88** [comment]
@erdivartanovich  have you push the newest one we just fixed downstair"?

**Pull request merged**
